<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.O5G1OAH' shared service.

return $this->privates['.service_locator.O5G1OAH'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\AnnonceController::createannonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\AnnonceController::newAnnonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\AnnonceController::supprimerAnnonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\SecurityController::login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController::changePassword' => ['privates', '.service_locator.Ow9IBJM', 'get_ServiceLocator_Ow9IBJMService.php', true],
    'App\\Controller\\UserController::changeUsername' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\UserController::register' => ['privates', '.service_locator.QSuQGoX', 'get_ServiceLocator_QSuQGoXService.php', true],
    'App\\Controller\\AnnonceController:createannonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\AnnonceController:newAnnonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\AnnonceController:supprimerAnnonce' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\SecurityController:login' => ['privates', '.service_locator.EbLunuf', 'get_ServiceLocator_EbLunufService.php', true],
    'App\\Controller\\UserController:changePassword' => ['privates', '.service_locator.Ow9IBJM', 'get_ServiceLocator_Ow9IBJMService.php', true],
    'App\\Controller\\UserController:changeUsername' => ['privates', '.service_locator.pe89cNF', 'get_ServiceLocator_Pe89cNFService.php', true],
    'App\\Controller\\UserController:register' => ['privates', '.service_locator.QSuQGoX', 'get_ServiceLocator_QSuQGoXService.php', true],
], [
    'App\\Controller\\AnnonceController::createannonce' => '?',
    'App\\Controller\\AnnonceController::newAnnonce' => '?',
    'App\\Controller\\AnnonceController::supprimerAnnonce' => '?',
    'App\\Controller\\SecurityController::login' => '?',
    'App\\Controller\\UserController::changePassword' => '?',
    'App\\Controller\\UserController::changeUsername' => '?',
    'App\\Controller\\UserController::register' => '?',
    'App\\Controller\\AnnonceController:createannonce' => '?',
    'App\\Controller\\AnnonceController:newAnnonce' => '?',
    'App\\Controller\\AnnonceController:supprimerAnnonce' => '?',
    'App\\Controller\\SecurityController:login' => '?',
    'App\\Controller\\UserController:changePassword' => '?',
    'App\\Controller\\UserController:changeUsername' => '?',
    'App\\Controller\\UserController:register' => '?',
]);
