<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCvWq7N8\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCvWq7N8/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerCvWq7N8.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerCvWq7N8\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerCvWq7N8\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'CvWq7N8',
    'container.build_id' => '3d501343',
    'container.build_time' => 1575899273,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCvWq7N8');
